import type { LevelDef } from '../core/level';

/** Generated by `npm run seeds` (tools/findSeeds.ts); every level is solver-verified in levels.test.ts. */
export const LEVELS: readonly LevelDef[] = [
  { id: 1, layoutId: 'threePeaks', seed: 100000, stockSize: 24, star2: 4, star3: 8 }, // best 13
  { id: 2, layoutId: 'threePeaks', seed: 200000, stockSize: 24, star2: 4, star3: 8 }, // best 13
  { id: 3, layoutId: 'threePeaks', seed: 300006, stockSize: 24, star2: 4, star3: 9 }, // best 14
  { id: 4, layoutId: 'threePeaks', seed: 400000, stockSize: 24, star2: 3, star3: 6 }, // best 10
  { id: 5, layoutId: 'threePeaks', seed: 500002, stockSize: 24, star2: 4, star3: 8 }, // best 12
  { id: 6, layoutId: 'pyramid', seed: 600121, stockSize: 22, star2: 2, star3: 5 }, // best 7
  { id: 7, layoutId: 'pyramid', seed: 700116, stockSize: 22, star2: 2, star3: 5 }, // best 8
  { id: 8, layoutId: 'pyramid', seed: 800005, stockSize: 22, star2: 2, star3: 5 }, // best 8
  { id: 9, layoutId: 'threePeaks', seed: 900003, stockSize: 22, star2: 2, star3: 4 }, // best 6
  { id: 10, layoutId: 'threePeaks', seed: 1000002, stockSize: 22, star2: 2, star3: 4 }, // best 6
  { id: 11, layoutId: 'threePeaks', seed: 1100002, stockSize: 22, star2: 2, star3: 5 }, // best 7
  { id: 12, layoutId: 'twinPeaks', seed: 1200004, stockSize: 20, star2: 2, star3: 5 }, // best 7
  { id: 13, layoutId: 'twinPeaks', seed: 1300004, stockSize: 20, star2: 1, star3: 3 }, // best 5
  { id: 14, layoutId: 'twinPeaks', seed: 1400005, stockSize: 20, star2: 3, star3: 6 }, // best 9
  { id: 15, layoutId: 'diamond', seed: 1505342, stockSize: 20, star2: 1, star3: 3 }, // best 4
  { id: 16, layoutId: 'diamond', seed: 1605237, stockSize: 20, star2: 1, star3: 3 }, // best 5
  { id: 17, layoutId: 'diamond', seed: 1700032, stockSize: 20, star2: 1, star3: 3 }, // best 4
  { id: 18, layoutId: 'wall', seed: 1800014, stockSize: 20, star2: 1, star3: 2 }, // best 3
  { id: 19, layoutId: 'wall', seed: 1900002, stockSize: 20, star2: 1, star3: 2 }, // best 3
  { id: 20, layoutId: 'wall', seed: 2000022, stockSize: 20, star2: 1, star3: 3 }, // best 5
  { id: 21, layoutId: 'threePeaks', seed: 2100000, stockSize: 18, star2: 1, star3: 2 }, // best 2
  { id: 22, layoutId: 'threePeaks', seed: 2200000, stockSize: 18, star2: 1, star3: 2 }, // best 2
  { id: 23, layoutId: 'threePeaks', seed: 2300000, stockSize: 18, star2: 1, star3: 3 }, // best 4
  { id: 24, layoutId: 'wall', seed: 2400081, stockSize: 16, star2: 1, star3: 2 }, // best 3
  { id: 25, layoutId: 'diamond', seed: 2503909, stockSize: 16, star2: 1, star3: 2 }, // best 2
];
